@host = https://localhost
@port = 7143
@Restaurants.API_HostAddress = https://localhost:7143

@userToken = CfDJ8DfErMmfcttFjDRphBFLYJFRsB-Rr4tLSspx4y5eag9PkgE1tcoqRy5lRKihN7wsRKo8ExVKoG4jKOPUmy8G5Iml7Snhvcum9Q_a17QP0MAxLCcOMc8TYguq7imayeL5QQEC8m6S0QImGrRQ24y1rUwVRaJg7Rip_8XWpQhNU0-kdu7tFDL4duGCsIptZITPRq-sNi-_EagNhm5kwjL1hkD-9HsthbAS8Nh04_KUv9Ao2jZpo3M_So3cgHRYBqInRyMx8X1ThqTn2IUL8C0Ke4_NrzGfrFa885TZDRf83THTj6w9IHFaInlxwtFiHX5kY9_4niHess3rZxdSAb5NrSH5y8ye6kcCGBJJFH9yc4HUcK4pvxBbHWwLq6_ALz_7IKMwmoowzD6J59COO1UgG9neDPlIcn0Owd03blonFuVaOrNi-A9x7M0EMX8b2vCiEQPykmJYpvOGQWSACUFoGi1SqMnz4wps-fn8bSkRhwj4ugyroGxF2DFjnEQlg-2BOgqs6fPD-eDVP9rSu8uJ63YT9WQY-mkKhJ0Jzsu2DhrpMvMrOf3-xzK0kk-EYjVEqObAfoxJ92tep8Bv0NpJNNo4i8TrtDOlkOx4gPK-x7dQm4TRyGAqsKpRX14OCxjfEOrP_pChHuWGJ_1BvDFM9a1_IDAVqtesinQz3E3mg5UMiBSQryF3RFBfKhbOl9yEaA
@ownerToken = CfDJ8DfErMmfcttFjDRphBFLYJHI2SEAvnomo_gLOKMqZ7twyhiThx6D8KlxRDDcc8HG4GMjTMw8rdUncIh_qxiNao3pLI3aP8ByVryu7McX-ynxmmT7ISNE5L5WWYT6fW_IAn_WTDeGH6nLrCcAgtEaxFZ1BiHkfJv62kTZyUQUjPB-cjgI1w5O5S_TpMfpRzhcPeaq-kpakjsDD--tas1u6Hu3UZWc-MZDkD1VWWToylOPTKTEjUFCQnGf9TJqmNVhlzyKCVfuXKbmgoGdSuf8OvK5Xn4S4zbTrvCrSzmGCe1bsWLmZcgVvVBO30_6tKb_VanEZ_MuibJVABqObyx_OWfCtFWh1o4zaUnNBEoC0EeDZnJ52Z_RTDxGhv-cW9n3ogKa2Jd0Sw14DqH8AeBzIvwA6XJ6darFy9pER8UZZRT9RUaYYNA1vwA4M050FXttXR4waD_SuRJ8VPllB786kzwCZi9kcXM32dMamEZ81GqMhVyyBJE1ba2mjrGMkKFZb-d2ou7MUa1991VXW4Ru2vzcls-FDfOcSSPiMOzY8AlTArGX4_8VeXlAI9VXfGlEwkgEkw_iYVMdUpYmhahUAVCRScKv5aC_45ylHLcm1G6vIXAB3OabGJHEJGWbxf4jfP6Ow1F3RH4GKDZv8ceJsWbLT-AnwpkLEe9SWq09ad2tzIRUX7uJiLZ201-6I8flzL9fqkuFWfPBMepdiVCYwhHVr7NP2Uxo8-pu_B9w_3Av21HwFPSEuT0uXCfvBNekQGMxGRCBNC7txYSxuqr8U6HN1A82UDv-QeZH9RaMaXIf
@adminToken = CfDJ8DfErMmfcttFjDRphBFLYJGD9btRs_4HaVnKEQNTgDBbvB558Tw8DqSD4a9AaAJh8dJSS_JyDPHNmQtkvkxpK8Q9NTuAuzREk7L19BzXt4JnWMkrZPPl-3haMiEs243HpqMouLVMnjgo8DVnwg7jVTR8f7ogGI9rNX1X1V9lDVRgMgYYd7AKKa_7e2-xxj0W4CleGuUvoQcIi1VACkcG3k37h58wWfmDWE3y2X-LKBzZXIOOOuGMxOh2qCC6GYweoV8DM5KR3YuPqNV8r8tkg6rUtKw3JOtZ5kCe-cfN7sqr8ofC6opKmSFJ4ZI9lwhaE2OR_zebeRlBPg59XhQnI06VaePkv9qDLi0hp3-KVQDvb07iPYeZVZ6bWWdZzNDky0xBH10_Bi7U2MAKUeRhy5nV6tBhRQaKSZTMNpHr-Q64XsyWlmKP-srOkGjzdloGn2S0DqPk9H_6ViAevXK4wKpWHCKh_tGRAnTmPlzyLmHK3JiAKlQ1lSYw9qNDTyG898HWYzAsn-qhnl8NdmdB3_QL43r_af5WoCOcVDhVPoiSGr_R6EtJ3wQgQwIqfiQzZ2p4B4F7WIaa0UjDUJsiptrXDn370cKP_eX0rRQH0-Keqn4t73_rdBx02qO_VpLK_sbunAc5RgNt7Ve3GSWssnmAPM0cfZGRLOANK_MO6tlVgfV8koOYljwhOdgi69dq7Q

GET {{Restaurants.API_HostAddress}}/api/weatherforecast/23/weather?max=15
Accept: application/json
Guid: {{$guid}}
LocalDate: {{$localDatetime iso8601}}
Random-integer: {{$randomInt}}

###

GET {{Restaurants.API_HostAddress}}/api/weatherforecast/CurrentDay
Accept: application/json

###

POST {{Restaurants.API_HostAddress}}/api/weatherforecast
Content-Type: application/json

"tarub"

###

POST {{Restaurants.API_HostAddress}}/api/weatherforecast/generate?take=3
Content-Type: application/json

{
  "minTemp": -100,
  "maxTemp": 120,
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/13
Authorization: Bearer {{ownerToken}}
Accept: application/json

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{ownerToken}}
Content-Type: application/json

{
  "Name" : "HATDOG NA BLUE",
  "Description": "MAINIT NA HOTDOG",
  "Category": "Chinese",
  "HasDelivery": true,
  "ContactEmail": "HATDOG@qweqwe.com",
  "ContactNumber": "093333333",
  "City": "Tokyo",
  "Street": "Shibuya",
  "PostalCode": "22-231"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1231231
Accept: application/json
###


PATCH {{Restaurants.API_HostAddress}}/api/restaurants/2
Content-Type: application/json

{
  "Name": "POGLOT3",
  "Description": "Fast Food",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/13/dishes
Content-Type: application/json

{
    "Name": "Chicken",
    "Description": "Nashville Chicken",
    "Price": 99.99,
    "KiloCalories": 43
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Accept: application/json
###


GET {{Restaurants.API_HostAddress}}/api/restaurants/13/dishes/12
Accept: application/json

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/13/dishes
Accept: application/json

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "email": "admin2@gmail.com",
  "password": "Password.12"
}


###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email": "owner@gmail.com",
  "password": "Password.12"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{$bearerToken}}
Content-Type: application/json


###
