@host = https://localhost
@port = 7143

@Restaurants.API_HostAddress = https://localhost:7143

GET {{Restaurants.API_HostAddress}}/api/weatherforecast/23/weather?max=15
Accept: application/json
Guid: {{$guid}}
LocalDate: {{$localDatetime iso8601}}
Random-integer: {{$randomInt}}

###

GET {{Restaurants.API_HostAddress}}/api/weatherforecast/CurrentDay
Accept: application/json

###

POST {{Restaurants.API_HostAddress}}/api/weatherforecast
Content-Type: application/json

"tarub"

###

POST {{Restaurants.API_HostAddress}}/api/weatherforecast/generate?take=3
Content-Type: application/json

{
  "minTemp": -100,
  "maxTemp": 120,
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants
Accept: application/json

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/13
Accept: application/json

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name" : "POGLOT2",
  "Description": "Paso de blas - POGLOT",
  "Category": "Japanese",
  "HasDelivery": true,
  "ContactEmail": "poglot@qweqwe.com",
  "ContactNumber": "234331232",
  "City": "Tokyo",
  "Street": "Shibuya",
  "PostalCode": "22-231"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1231231
Accept: application/json
###


PATCH {{Restaurants.API_HostAddress}}/api/restaurants/2
Content-Type: application/json

{
  "Name": "POGLOT3",
  "Description": "Fast Food",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/13/dishes
Content-Type: application/json

{
    "Name": "Chicken",
    "Description": "Nashville Chicken",
    "Price": 99.99,
    "KiloCalories": 43
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Accept: application/json
###


GET {{Restaurants.API_HostAddress}}/api/restaurants/13/dishes/12
Accept: application/json

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/13/dishes
Accept: application/json
###
