@host = https://localhost
@port = 7143
@Restaurants.API_HostAddress = https://localhost:7143
@token = CfDJ8DfErMmfcttFjDRphBFLYJFKdPQ3MJSPj56uiyldwaG3ubKW4aCXDpYjLcqo51oEMCRkCqcCTb7OZ95-VVv3-YjYQezRvp6PqBQq6rxmdm-LSkpE-ud8Vx9dWr0D_mIM-oqdqwnZ3YeXX-wNUlGzEIwy2BGYcKCoGptgeglSay2p7ab2-LaBYU8cl2YAKShHEWJHPZ6zU10or_4OgAAXImR_PsTWAYTRxWCVrT4qK9HIqMcxMRdcLkSgaqVBBM4f6t7k-IQEROCWTue2r-sfkx29pjH-iBmdHcY0xpTMm2vrEojxxK5ze0ai_XAlNMzutBzLf1lLVLLFPDPtDUvlO1Y17qT5CoDtr6GurGE2LAfRInwoWVozGO-yObfEPeA9D2o4SEuWC5JK-42oOIPHIvG94-SjAttXXUaKbA_rIiTQ8u1j-ZDNCAZ7v2u8lHnWI7_FuNFaJpffDAtr-SjyXA7gksmsf2PY8PQ20XjBngEmywtWooyg7sFEWDpcL0PVDrKSXvOVehBK-xObbhGB6fgeyMW-wKDUEf9VQ2Kz2ifwSv8gcWqsnEercK6dftg-zrtryqGMc4iNCBf-2DqsWW93jfsFHOmfovQ9RS1quzlFApm7VwN9MdPBNDhU1ZVrvtfhGBxOcjzsmmwVSjFb7hOyFI7iFFfiymsboVYKCHgkhyL1zMvh_M8tN4OhmrYHeVoRYctWMd5iJI2dE3e84AjywNCivJdxmMNBSM2vx8wz5POmbl-rHWbAf9ynV_SFhpUUPmMywZdT7XCefi4EpjRniwxkV_MVR6KpSDYqLhSs8ZzhbZvcVIckC397wU1srTBogp8AwUMaQv8Ks1EkPVNVVnYrTZSRJWEis2fAJnGecSqVd9LxL-5KJ-yD-Z9C8Q
@userToken = CfDJ8DfErMmfcttFjDRphBFLYJFRsB-Rr4tLSspx4y5eag9PkgE1tcoqRy5lRKihN7wsRKo8ExVKoG4jKOPUmy8G5Iml7Snhvcum9Q_a17QP0MAxLCcOMc8TYguq7imayeL5QQEC8m6S0QImGrRQ24y1rUwVRaJg7Rip_8XWpQhNU0-kdu7tFDL4duGCsIptZITPRq-sNi-_EagNhm5kwjL1hkD-9HsthbAS8Nh04_KUv9Ao2jZpo3M_So3cgHRYBqInRyMx8X1ThqTn2IUL8C0Ke4_NrzGfrFa885TZDRf83THTj6w9IHFaInlxwtFiHX5kY9_4niHess3rZxdSAb5NrSH5y8ye6kcCGBJJFH9yc4HUcK4pvxBbHWwLq6_ALz_7IKMwmoowzD6J59COO1UgG9neDPlIcn0Owd03blonFuVaOrNi-A9x7M0EMX8b2vCiEQPykmJYpvOGQWSACUFoGi1SqMnz4wps-fn8bSkRhwj4ugyroGxF2DFjnEQlg-2BOgqs6fPD-eDVP9rSu8uJ63YT9WQY-mkKhJ0Jzsu2DhrpMvMrOf3-xzK0kk-EYjVEqObAfoxJ92tep8Bv0NpJNNo4i8TrtDOlkOx4gPK-x7dQm4TRyGAqsKpRX14OCxjfEOrP_pChHuWGJ_1BvDFM9a1_IDAVqtesinQz3E3mg5UMiBSQryF3RFBfKhbOl9yEaA
@ownerToken = CfDJ8DfErMmfcttFjDRphBFLYJHNGKKT3MLgX8kx0fC3nnv0XnSW05B8AFDKZRmGteAcMOp9acWGnQNpJrE6rBYZRo70bvnhruIJTOEMe6c3Zj-y4laOGZ6TzedfOIzosqDechldTfStySbMfSA1fMc8FfSByZcfAwtCblJNK-hrAIkW-tAxJiRFeBm_tnADlWceO-GfHL1dL3aVNnaW1_cUvwyipxKRiDTYTPwP6CB7B-THQc8Lbnj4oLprORSXq8Of8brrEWwBhpOPyTlcuLKnj94OCIm7VpB-smPVWMqIVVcdgm8qcXty6qdiH6efzaLGjYQAZr3fwVmR93USHr7HLS_swErbPIytElZIG8x4F1jFDt7XAABSmDTT00q4tHj05zNlErDLosSRzWVUOD3X_o2WSqswoOrdxrayafsNpt5I9hBbCZMFQ6_2caVvRqam2s8GCjmajFwDbyVcLOgKHwffzjnLn8CGgGW_GvnCS3NDm62-B-Fk6jICWNhili5sTKGoew-axEryBS6NmaLywUHFXlAkzfeYLXGHwdgzHbcPUksi4pXraBFnbs5LdMOz0OeLvAXzwu2C44a0E3EJwknN341Ud3MwG7vZoB1rnaUvI2dKNqitdNqW4M2j4k7baYmrxfvKAieeX8whtWmjAajMbnfEWDdkM41zDilTFg5imDhUeaLxb9Ze6ia1QQevF5JgfRkA9VNkp70X8aaUvbJbVWr1gOJLwRcBsWjWU2s8JOih2M9hfaqaA6yQJ794PuZXMSACfMR2QX1sHbu9hsyNYwA6jV8SRmEc8Gq5TxdeWDTiLGtdsFashr0R4Zn0KOTC1EkkzQOk6xSMrlLnqb0stWOFiyZxrZ1wxLhgdUmuwIbDX-M5Gk9-qmoYIeOVXA
@adminToken = CfDJ8DfErMmfcttFjDRphBFLYJGvBymPXx4n4iqM8h-Whhn4QjDrcvv1mBF1ANyQ7Okz5nMSk9-X7l-wfo4DTfqKQ-UconPoWqudt7q0kcHHFdwgBQqpUmK4qOAwzc87zaSctTD2jz3eRg4i-VZlobHLLyeYUCPLXjgKbvkfiC06Y2BolKo5JPlON92l7yrwGQPMX7b1GTjNYYKLaWQCZxftv9hFpsi53tU6JnEfNgRZhrhuPowpuKG2Y9l2nHkGaOPvAoE_JPwLEECyDZR-Cr7Ag5eg9SA7mtqE2FQPNTFU06Jrj5I9dKtJmkNymtaDABf9lSFGlekJio8rCkXHsXo52nyVx_YFmNDKdQme3ghFJ9Xb0iwZFO_KFQFc3n1j1DBJGn5a7jkelNScJCOMP7DXroibE1FomrIdwBwFQK2T550QeGvD-0e9-hAtHdicfTMu_3iZ6DRE2jQ3OH72lTb6Yxa0Phum8LVPR3VsmGjlz6CUoO537oI2VR5n_Ibu5la7Sm51puzF-MfpreEr_A9zP-VGjefLj2hYzqKhyJ11Rop6iwp9e_ixgjVVqxjFz5Rr-RT66xg66sMBVej18L4nov10kViiqpxofOj3hXnpfimxX-BBv73kagUdCWpaY5oyPX4ubO8NY7jT3Q9y2-6nlSt5cMARatz2BjoR3xPTZyPOrBAl_RSf2bM_zp9laHHK2WKn9getGPJzXWDdmiZPbmKApFji1BZ4wvXlZBKTLM_xFw7VfqdStrM32n_tqRuUI0OkxmAe0SUK0xBFOVaar7jd3Ml0DrxyuWdilgmPQ_hT

GET {{Restaurants.API_HostAddress}}/api/weatherforecast/23/weather?max=15
Accept: application/json
Guid: {{$guid}}
LocalDate: {{$localDatetime iso8601}}
Random-integer: {{$randomInt}}

###

GET {{Restaurants.API_HostAddress}}/api/weatherforecast/CurrentDay
Accept: application/json

###

POST {{Restaurants.API_HostAddress}}/api/weatherforecast
Content-Type: application/json

"tarub"

###

POST {{Restaurants.API_HostAddress}}/api/weatherforecast/generate?take=3
Content-Type: application/json

{
  "minTemp": -100,
  "maxTemp": 120,
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Accept: application/json

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/17
Authorization: Bearer {{ownerToken}}
Accept: application/json

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{ownerToken}}
Content-Type: application/json

{
  "Name" : "HATDOG NA RED",
  "Description": "MAINIT NA HOTDOG RED",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "HATDOGRED@qweqwe.com",
  "ContactNumber": "094444444",
  "City": "Tokyo",
  "Street": "Shiratorizawa",
  "PostalCode": "22-231"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1231231
Accept: application/json
###


PATCH {{Restaurants.API_HostAddress}}/api/restaurants/2
Content-Type: application/json

{
  "Name": "POGLOT3",
  "Description": "Fast Food",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Content-Type: application/json

{
    "Name": "Chicken",
    "Description": "Nashville Chicken",
    "Price": 99.99,
    "KiloCalories": 43
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes
Authorization: Bearer {{token}}
Accept: application/json
###


GET {{Restaurants.API_HostAddress}}/api/restaurants/13/dishes/12
Accept: application/json

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/13/dishes
Accept: application/json

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json
{
  "email": "admin2@gmail.com",
  "password": "Password.12"
}


###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email": "owner@gmail.com",
  "password": "Password.12"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "Nationality": "TANGALOG",
  "DateOfBirth" : "2001-10-07"
}


###
